# User Test
#------------------------------------
APP              = cli
# App sources
APP_SRCS         = cli.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       =
# Linker flags
APP_LDFLAGS      =

# Custom linker
APP_LINK_SCRIPT  =

include $(RULES_DIR)/pmsis_rules.mk
