# User Test
#------------------------------------------
TEST_C          = ./test_OSPI_MACRONIX.c

# RTL Simulation
#------------------------------------------
recordWlf=YES
vsimDo="-do ~/wave/vega_wave_octo.do"

vsimPadMuxMode="TB_PADMUX_OCTO_SPI_FLASH"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
