# User Test
#------------------------------------
APP_SRC 	= ./main_SAI_Async.c
DEMO_SRC	+=
INCLUDES	+=

PLPBRIDGE_FLAGS += -s i2s@../../../i2s.py

include $(GAP_SDK_HOME)/tools/rules/freeRTOS_rules.mk
