APP         = test_connection_with_android_app
APP_SRCS    = test_android_app.c tx_rx_with_android.c
APP_CFLAGS  =
APP_LDFLAGS =

DEBUG=1
DEVICE_CONNECTED=1
CONFIG_BLE_NINA_B312=1

include $(RULES_DIR)/pmsis_rules.mk
