# User Test
#------------------------------------

APP              = i2c_probe_slave
APP_SRCS        += i2c_probe_slave.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
