ifeq '$(fll/version)' '1'
IMPLEMENTATIONS += pulp/fll/fll_v1_impl
pulp/fll/fll_v1_impl_SRCS = pulp/fll/fll_v1_impl.cpp
endif

ifeq '$(fll/version)' '2'
IMPLEMENTATIONS += pulp/fll/fll_v2_impl
pulp/fll/fll_v2_impl_SRCS = pulp/fll/fll_v2_impl.cpp
endif

IMPLEMENTATIONS += pulp/fll/fll_ctrl_impl
pulp/fll/fll_ctrl_impl_SRCS = pulp/fll/fll_ctrl_impl.cpp
