# User Test
#------------------------------------

APP              = test
APP_SRCS        += test_gap.c
APP_INC	        += .
APP_CFLAGS      +=
APP_LDFLAGS     +=

# Include GAP_LIB/IMGIO
CONFIG_GAP_LIB_IMGIO = 1

BOARD_NAME = gapoc_b
io=host

include $(RULES_DIR)/pmsis_rules.mk
