# User Test
#------------------------------------

APP              = test
APP_SRCS        += helloworld.c
APP_INC	        +=
APP_CFLAGS      +=

export GAP_USE_OPENOCD=1
include $(RULES_DIR)/pmsis_rules.mk
