IMPLEMENTATIONS += pulp/adv_dbg_unit/adv_dbg_unit_impl pulp/adv_dbg_unit/riscv_dtm_impl

COMPONENTS += pulp/adv_dbg_unit/adv_dbg_unit pulp/adv_dbg_unit/riscv_dtm

pulp/adv_dbg_unit/adv_dbg_unit_impl_SRCS = pulp/adv_dbg_unit/adv_dbg_unit_impl.cpp

pulp/adv_dbg_unit/riscv_dtm_impl_SRCS = pulp/adv_dbg_unit/riscv_dtm_impl.cpp
