# User Test
#------------------------------------------
TEST_C          = ./test_CSI2_I3C.c

# RTL Simulation
#------------------------------------------
# recordWlf=YES
# vsimDo="-do ~/wave/vega_wave_csi2.do"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
