# User Test
#------------------------------------

APP              = test
APP_SRCS        += decompressor_mode_T1.c
APP_INC         +=
APP_CFLAGS      +=

override PMSIS_OS = freertos

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
