# User Test
#------------------------------------

APP              = test
APP_SRCS        += blink_led.c
APP_INC	        +=
APP_CFLAGS      +=

BOARD_NAME ?= gapoc_a

include $(RULES_DIR)/pmsis_rules.mk
