# User Test
#------------------------------------

APP              = test_udma_fifo_event_cb
APP_SRCS         = test_udma_fifo_event_cb.c
APP_INC	         =
APP_CFLAGS       =
APP_LDFLAGS      =

override PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
