# User Test
#------------------------------------------
TEST_C          = ./test_SDIO.c

# For SDIO test
#------------------------------------------
vsimPadMuxMode=TB_PADMUX_SDIO

# RTL Simulation
#------------------------------------------
recordWlf=YES
vsimDo="-do ~/wave/vega_wave_sd.do"

chip=GAP9

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
