# User Test
#------------------------------------

APP              = test
APP_SRCS        += i2c_master_freq.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
