ifeq '$(padframe/version)' '1'
IMPLEMENTATIONS += pulp/padframe/padframe_v1_impl
COMPONENTS += pulp/padframe/padframe_v1
pulp/padframe/padframe_v1_impl_SRCS = pulp/padframe/padframe_v1_impl.cpp
endif
