# User Test
#------------------------------------------
TEST_C          = ./test_Serial.c

# RTL Simulation
#------------------------------------------
# recordWlf=YES
# vsimDo="-do ~/wave.do"

vsimPadMuxMode="TB_PADMUX_UART2"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
