# User Test
#------------------------------------

APP              = test
APP_SRCS        += helloworld.c
APP_INC	        +=
APP_CFLAGS      +=
APP_LDFLAGS     +=

CONFIG_OPENMP=1

include $(RULES_DIR)/pmsis_rules.mk
