# User Test
#------------------------------------

APP              = test_decomp_l2_2d_l1_1d
APP_SRCS        += test_decomp_l2_2d_l1_1d.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
