# User Test
#------------------------------------

APP              = test_dmacpy_l2_l2_async
APP_SRCS         = test_dmacpy_l2_l2_async.c
APP_INC          =
APP_LDFLAGS      =

override PMSIS_OS = freertos

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
