# User Test
#------------------------------------

APP              = test
APP_SRCS        += test_pwm.c
APP_INC	        +=
APP_CFLAGS      +=

override PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
