# User Test
#------------------------------------
APP_SRC 	= ./main_SPI_S25FS256S_NON_QPI.c
DEMO_SRC	+=
INC_PATH	+=

FREERTOS_FLAGS 	+= -DSPI_QPI=0

include $(GAP_SDK_HOME)/tools/rules/freeRTOS_rules.mk
