# User Test
#------------------------------------------
TEST_C          = ./test_DBG.c

# RTL Simulation
#------------------------------------------
# recordWlf=YES
# vsimDo="-do ~/wave/wave_efuse.do"

chip=GAP9

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
