ifdef udma/hyper/version

IMPLEMENTATIONS += devices/hyperbus/hyperram_impl
devices/hyperbus/hyperram_impl_SRCS = devices/hyperbus/hyperram_impl.cpp

IMPLEMENTATIONS += devices/hyperbus/hyperflash_impl
devices/hyperbus/hyperflash_impl_SRCS = devices/hyperbus/hyperflash_impl.cpp

endif