# User Test
#------------------------------------

APP              = test_decomp_l2_1d_l1_2d
APP_SRCS        += test_decomp_l2_1d_l1_2d.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
