# User Test
#------------------------------------

APP              = test
APP_SRCS        += decompressor_automatic_test.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
