ifeq '$(hwce/version)' '4'
IMPLEMENTATIONS += pulp/hwce/hwce_v4_impl
COMPONENTS += pulp/hwce/hwce_v4
pulp/hwce/hwce_v4_impl_SRCS = pulp/hwce/hwce_v4_impl.cpp
endif

#ifeq '$(hwce/version)' '5'
#IMPLEMENTATIONS += pulp/hwce/hwce_v5_impl
#COMPONENTS += pulp/hwce/hwce_v5
#pulp/hwce/hwce_v5_impl_SRCS = pulp/hwce/hwce_v5_impl.cpp
#endif