# User Test
#------------------------------------------
TEST_C          = ./test_Cluster_TCDM_COMPRESS.c

# If you do not want to use RTOS, comment it.
# If you want use RTOS then uncomment it.
# MBED_FLAGS     += -DMBED_CONF_RTOS_PRESENT=1

# RTL Simulation
#------------------------------------------
# recordWlf=YES
# vsimDo="-do ~/dma.do"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
