# User Test
#------------------------------------------
TEST_C          = ./test_OSPI_SINGLE.c

# RTL Simulation
#------------------------------------------
recordWlf=YES
vsimDo="-do ~/wave/vega_wave_octo.do"

vsimPadMuxMode="TB_PADMUX_OCTO_SPI"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
