ifeq '$(dma/version)' '6'
IMPLEMENTATIONS += pulp/mchan/mchan_v6_impl
pulp/mchan/mchan_v6_impl_SRCS = pulp/mchan/mchan_v6_impl.cpp
endif

ifeq '$(dma/version)' '7'
IMPLEMENTATIONS += pulp/mchan/mchan_v7_impl
pulp/mchan/mchan_v7_impl_SRCS = pulp/mchan/mchan_v7_impl.cpp
endif
