# User Test
#------------------------------------
APP              = helloworld
# App sources
APP_SRCS         = helloworld.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       =
# Linker flags
APP_LDFLAGS      =

# Custom linker
APP_LINK_SCRIPT  =

PMSIS_OS = freertos
#BOARD_NAME ?= gapuino

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
