IMPLEMENTATIONS += interco/router_impl interco/interleaver_impl interco/bus_watchpoint interco/router_proxy

interco/router_impl_SRCS = interco/router_impl.cpp
interco/interleaver_impl_SRCS = interco/interleaver_impl.cpp

IMPLEMENTATIONS += interco/converter_impl
interco/converter_impl_SRCS = interco/converter_impl.cpp

interco/bus_watchpoint_SRCS = interco/bus_watchpoint.cpp

interco/router_proxy_SRCS = interco/router_proxy.cpp
