IMPLEMENTATIONS += interco/router_impl interco/interleaver_impl

COMPONENTS += interco/router interco/interleaver

interco/router_impl_SRCS = interco/router_impl.cpp
interco/interleaver_impl_SRCS = interco/interleaver_impl.cpp

IMPLEMENTATIONS += interco/converter_impl
COMPONENTS += interco/converter
interco/converter_impl_SRCS = interco/converter_impl.cpp
