IMPLEMENTATIONS += interco/router_impl interco/interleaver_impl

interco/router_impl_SRCS = interco/router_impl.cpp
interco/interleaver_impl_SRCS = interco/interleaver_impl.cpp

IMPLEMENTATIONS += interco/converter_impl
interco/converter_impl_SRCS = interco/converter_impl.cpp
