# Copyright (C) 2020 Padrone AG
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the BSD license. See the LICENSE file for details.

PULP_APP = test
PULP_APP_FC_SRCS = efuse.c

include $(GAP_SDK_HOME)/tools/rules/pulp_rules.mk
