# User Test
#------------------------------------

APP              = ffc_bench
APP_SRCS        += ffc_bench.c
APP_INC         +=
APP_CFLAGS      +=

#PMSIS_OS=freertos

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
