ifeq '$(pmu/version)' '1'
IMPLEMENTATIONS += pulp/pmu/pmu_v1_impl
pulp/pmu/pmu_v1_impl_SRCS = pulp/pmu/pmu_v1_impl.cpp
endif

ifeq '$(pmu/version)' '2'
IMPLEMENTATIONS += pulp/pmu/pmu_v2_impl
pulp/pmu/pmu_v2_impl_SRCS = pulp/pmu/pmu_v2_impl.cpp
endif

ifeq '$(pmu/version)' '3'
IMPLEMENTATIONS += pulp/pmu/pmu_v3_impl
pulp/pmu/pmu_v3_impl_SRCS = pulp/pmu/pmu_v3_impl.cpp
endif

ifeq '$(pmu/version)' '4'
IMPLEMENTATIONS += pulp/pmu/pmu_v4_impl
pulp/pmu/pmu_v4_impl_SRCS = pulp/pmu/pmu_v4_impl.cpp
endif
