# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite_schema_head

class SparseIndexVector(object):
    NONE = 0
    Int32Vector = 1
    Uint16Vector = 2
    Uint8Vector = 3
