# User Test
#------------------------------------

APP              = ffc_all_periphs
APP_SRCS        += ffc_all_periphs.c ../ffc_utils/ffc_test_utils.c
APP_INC         += ../ffc_utils
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
