# User Test
#------------------------------------

APP              = test
APP_SRCS        += aes_multiple_devices.c
APP_INC         +=
APP_CFLAGS      +=

PMSIS_OS=freertos

CONFIG_AES=1

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
