# User Test
#------------------------------------
APP_SRC 	= ./main_Tasks.c
DEMO_SRC	+=
INC_PATH	+=

# Uncomment to disable preemptive scheduling
# NO_PREEMPTION	= true

include $(GAP_SDK_HOME)/tools/rules/freeRTOS_rules.mk
