# User Test
#------------------------------------

APP              = test_udma_fifo_aes_both_ends
APP_SRCS        += test_udma_fifo_aes_both_ends.c
APP_INC         +=
APP_CFLAGS      +=

CONFIG_AES=1

override PMSIS_OS=freertos

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
