# User Test
#------------------------------------

APP              = test
APP_SRCS        += rtc_calendar.c
APP_INC         +=
APP_CFLAGS      +=

# Uncomment to disable preemptive scheduling
# NO_PREEMPTION	= true

PMSIS_OS = freertos
BOARD_NAME ?= gapuino

include $(GAP_SDK_HOME)/tools/rules/pmsis_rules.mk
