# User Test
#------------------------------------

APP_LINK_SCRIPT	 = ./GAP9.ld
APP              = test
APP_SRCS        += helloworld_xip.c
APP_INC	        +=
APP_CFLAGS      +=

include $(RULES_DIR)/pmsis_rules.mk
