ifeq '$(icache_ctrl/version)' '2'
IMPLEMENTATIONS += pulp/icache_ctrl/icache_ctrl_v2_impl
COMPONENTS += pulp/icache_ctrl/icache_ctrl_v2
pulp/icache_ctrl/icache_ctrl_v2_impl_SRCS = pulp/icache_ctrl/icache_ctrl_v2_impl.cpp
endif