# User Test
#------------------------------------
APP              = test
# App sources
APP_SRCS         = sw_reset.c
# App includes
APP_INC	         =
# Compiler flags
APP_CFLAGS       =
# Linker flags
APP_LDFLAGS      =

# Custom linker
APP_LINK_SCRIPT  =

override PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
