# User Test
#------------------------------------

APP              = test
APP_SRCS         = blink_led.c
APP_INC	         =
APP_CFLAGS       =
APP_LDFLAGS      =

include $(RULES_DIR)/pmsis_rules.mk
