ifeq '$(udma/mram/version)' '1'

VP_HEADERS += pulp/mram/mram.hpp

IMPLEMENTATIONS += pulp/mram/mram_v1_impl
COMPONENTS += pulp/mram/mram_v1
pulp/mram/mram_v1_impl_SRCS = pulp/mram/mram_impl.cpp

endif
