ifeq '$(soc_eu/version)' '1'
IMPLEMENTATIONS += pulp/soc_eu/soc_eu_v1_impl
COMPONENTS += pulp/soc_eu/soc_eu_v1
pulp/soc_eu/soc_eu_v1_impl_SRCS = pulp/soc_eu/soc_eu_v1_impl.cpp
endif

ifeq '$(soc_eu/version)' '2'
IMPLEMENTATIONS += pulp/soc_eu/soc_eu_v2_impl
COMPONENTS += pulp/soc_eu/soc_eu_v2
pulp/soc_eu/soc_eu_v2_impl_SRCS = pulp/soc_eu/soc_eu_v2_impl.cpp
endif