# User Test
#------------------------------------

APP              = test
APP_SRCS        += aes_cbc_crypt_128.c
APP_INC         +=
APP_CFLAGS      +=

CONFIG_AES=1

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
