__ZERO  = 0;
__USE_UART = 0;
__RT_DEBUG_CONFIG   = (0 << 8) | 0;
__FC   = 1;
__L2   = 0x80000;
__L1Cl = 0x10000;
__FETCH_ALL = 0x0;
__ACTIVE_FC = 0x1;
__rt_stack_size = 0x800;
__NB_ACTIVE_PE = 8;
__rt_nb_cluster = 1;
__rt_nb_pe = 8;
__rt_cl_master_stack_size = 0x400;
__rt_cl_slave_stack_size = 0x400;
__rt_config = 0x0;
__rt_debug_init_config = 0x3;
__rt_debug_init_config_trace = 0x0;
GROUP( -lgloss -lgcc )
