# User Test
#------------------------------------

APP              = test_udma_datamove_lin_2d
APP_SRCS         = test_udma_datamove_lin_2d.c
APP_INC	         =
APP_CFLAGS       =
APP_LDFLAGS      =

override PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
