# User Test
#------------------------------------

APP              = test
APP_SRCS        += main_EventGroup.c
APP_INC         +=
APP_CFLAGS      +=

PMSIS_OS = freertos
BOARD_NAME ?= gapuino

include $(GAP_SDK_HOME)/tools/rules/pmsis_rules.mk
