ifdef udma/hyper/version
IMPLEMENTATIONS += devices/hyperchip/hyperchip_impl
COMPONENTS += devices/hyperchip/hyperchip
devices/hyperchip/hyperchip_impl_SRCS = devices/hyperchip/hyperchip_impl.cpp
endif