ifeq '$(fll/version)' '1'
IMPLEMENTATIONS += pulp/fll/fll_v1_impl
COMPONENTS += pulp/fll/fll_v1
pulp/fll/fll_v1_impl_SRCS = pulp/fll/fll_v1_impl.cpp
endif

IMPLEMENTATIONS += pulp/fll/fll_ctrl_impl
COMPONENTS += pulp/fll/fll_ctrl
pulp/fll/fll_ctrl_impl_SRCS = pulp/fll/fll_ctrl_impl.cpp
