# User Test
#------------------------------------

APP              = test
APP_SRCS         = test_timer.c
APP_INC	         =
APP_CFLAGS       =
APP_LDFLAGS      =

PMSIS_OS         = freertos

include $(RULES_DIR)/pmsis_rules.mk
