# User Test
#------------------------------------------
TEST_C          = ./test_HYPER_RAM.c

# RTL Simulation
#------------------------------------------
recordWlf=YES
vsimDo="-do ~/wave/vega_wave_octo.do"

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
