# User Test
#------------------------------------
APP              = test
# App sources
APP_SRCS         = test_thermeye.c
# App includes
APP_INC	         = .
# Compiler flags
APP_CFLAGS       =
# Linker flags
APP_LDFLAGS      =

# Include GAP_LIB/IMGIO
CONFIG_GAP_LIB_IMGIO = 1

BOARD_NAME = gapoc_b
io=host

include $(RULES_DIR)/pmsis_rules.mk
