# User Test
#------------------------------------

APP              = test
APP_SRCS        += test_thermeye.c
APP_INC	        += .
APP_CFLAGS      +=
APP_LDFLAGS     += #-lgaplib

CONFIG_GAP_LIB = 1
BOARD_NAME = gapoc_b
io=host

include $(RULES_DIR)/pmsis_rules.mk
