PULP_APP = test
PULP_APP_FC_SRCS = test_sensorboard.c
PULP_CFLAGS = -O3 -g

#PULP_CFLAGS += -DFORCE_TEST_FAIL #each sensor has then a wrong I2C address

include $(GAP_SDK_HOME)/tools/rules/pulp_rules.mk

