# User Test
#------------------------------------

APP              = ffc_open_close
APP_SRCS        += ffc_open_close.c
APP_INC         +=
APP_CFLAGS      +=

PMSIS_OS=freertos
CONFIG_AES=1

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
