# User1;2802;0c Test
#------------------------------------------
TEST_C          = ./test_I2C_M24M02.c

# For RTOS Jenkins test, it will never finished so add a jenkins test Flag to exit().
# MBED_FLAGS     +=-DJENKINS_TEST_FLAG=1

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
