#define	SAMPLERATE                16000
#define	FRAME_SIZE                  640
#define	FRAME_STEP                  320
#define	N_FFT                      1024
#define	DATA_TYPE                     0
#define	MFCC_BANK_CNT                40
#define	FMIN                       20.0
#define	FMAX                     4000.0
#define	MFCC_COEFF_CNT              494
#define	N_DCT                        40
