# User Test
#------------------------------------
APP_SRC 	= ./main_Sleep.c
DEMO_SRC	+=
INC_PATH	+=

#PLPBRIDGE_FLAGS	+= -f -hyper
#FREERTOS_FLAGS 	+= -DPRINTF_UART=1

include $(GAP_SDK_HOME)/tools/rules/freeRTOS_rules.mk
