IMPLEMENTATIONS += vp/clock_domain_impl vp/time_domain_impl vp/trace_domain_impl vp/power_engine_impl

COMPONENTS += vp/clock_domain vp/time_domain vp/trace_engine vp/power_engine

vp/clock_domain_impl_SRCS = vp/clock_domain_impl.cpp

vp/time_domain_impl_SRCS = vp/time_domain_impl.cpp

vp/trace_domain_impl_SRCS = vp/trace_domain_impl.cpp

vp/power_engine_impl_SRCS = vp/power_engine_impl.cpp
