IMPLEMENTATIONS += vp/clock_domain_impl vp/time_domain_impl vp/trace_domain_impl vp/power_engine_impl

vp/clock_domain_impl_SRCS = vp/clock_domain_impl.cpp

vp/time_domain_impl_SRCS = vp/time_domain_impl.cpp

vp/trace_domain_impl_SRCS = vp/trace_domain_impl.cpp
vp/trace_domain_impl_LDFLAGS = -lpthread

vp/power_engine_impl_SRCS = vp/power_engine_impl.cpp
