IMPLEMENTATIONS += devices/i2c/eeprom/i2c_eeprom

devices/i2c/eeprom/i2c_eeprom_SRCS += devices/i2c/eeprom/i2c_eeprom.cpp
devices/i2c/eeprom/i2c_eeprom_SRCS += $(GVSOC_SRC_PATH)/models/devices/i2c/helper/i2c_helper.cpp

devices/i2c/eeprom/i2c_eeprom_CFLAGS += -I$(GVSOC_SRC_PATH)/models/devices/i2c/helper/
