# User Test
#------------------------------------
APP_SRC		 = ./main_Bridge.c
DEMO_SRC	+=
INC_PATH	+=

PLPBRIDGE_FLAGS += -fileIO

clean::
	rm -rf out_Bridge.c

include $(GAP_SDK_HOME)/tools/rules/freeRTOS_rules.mk
