# User Test
#------------------------------------------
TEST_C          = ./test_CSI2.c

# RTL Simulation
#------------------------------------------
# recordWlf=YES
# vsimDo="-do ~/wave/vega_wave_csi2.do"

vsimPadMuxMode=TB_PADMUX_CSI2

include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
