ifeq '$(pulp_chip)' 'multino'
IMPLEMENTATIONS += pulp/chips/multino/apb_soc_impl
COMPONENTS += pulp/chips/multino/apb_soc
pulp/chips/multino/apb_soc_impl_SRCS = pulp/chips/multino/apb_soc_impl.cpp
endif
