# User Test
#------------------------------------

APP              = test
APP_SRCS        += decompressor_sw_fifo.c
APP_INC         +=
APP_CFLAGS      += -Os

override PMSIS_OS = freertos

include $(GAP_SDK_HOME)/utils/rules/pmsis_rules.mk
