# User Test
#------------------------------------

APP              = test
APP_SRCS        += i2c_eeprom_pulp_fmc.c
APP_INC         +=
APP_CFLAGS      +=

include $(GAP_SDK_HOME)/tools/rules/pmsis_rules.mk
