IMPLEMENTATIONS += devices/i2c/corruptor/i2c_corruptor

devices/i2c/corruptor/i2c_corruptor_SRCS += devices/i2c/corruptor/i2c_corruptor.cpp
devices/i2c/corruptor/i2c_corruptor_SRCS += $(GVSOC_SRC_PATH)/models/devices/i2c/helper/i2c_helper.cpp

devices/i2c/corruptor/i2c_corruptor_CFLAGS += -I$(GVSOC_SRC_PATH)/models/devices/i2c/helper/
