ifeq '$(event_unit/version)' '3'
IMPLEMENTATIONS += pulp/event_unit/eu_v3_impl
pulp/event_unit/eu_v3_impl_SRCS = pulp/event_unit/eu_v3_impl.cpp
endif

ifeq '$(event_unit/version)' '4'
IMPLEMENTATIONS += pulp/event_unit/eu_v4_impl
pulp/event_unit/eu_v4_impl_SRCS = pulp/event_unit/eu_v4_impl.cpp
endif