onerror {resume}
quietly virtual signal -install /tb/pulp_chip_iface_i { (context /tb/pulp_chip_iface_i )&{pad_hyper0_dq7 , pad_hyper0_dq6 , pad_hyper0_dq5 , pad_hyper0_dq4 , pad_hyper0_dq3 , pad_hyper0_dq2 , pad_hyper0_dq1 , pad_hyper0_dq0 }} dq
quietly WaveActivateNextPane {} 0
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_hyper0_ckn
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_hyper0_ck
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_hyper0_csn0
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_hyper0_csn1
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_hyper0_rwds
add wave -noupdate -group pad /tb/pulp_chip_iface_i/dq
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c0_sda
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c0_scl
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c1_sda
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c1_scl
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c2_sda
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i2c2_scl
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i3c_sda
add wave -noupdate -group pad /tb/pulp_chip_iface_i/pad_i3c_scl
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/clk_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/rst_ni
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/clock_en_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/test_en_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/fregfile_disable_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/boot_addr_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/core_id_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/cluster_id_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_req_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_gnt_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_rvalid_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_addr_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_rdata_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_cache_flush_req_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/instr_cache_flush_gnt_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_req_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_gnt_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_rvalid_i
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_we_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_be_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_addr_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_wdata_o
add wave -noupdate -group FC /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/fc_subsystem_i/FC_CORE/data_rdata_i
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sys_clk_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/periph_clk_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/rstn_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/test_mode_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/scl_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/scl_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/scl_oe}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sda_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sda_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sda_oe}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_data_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_addr_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_valid_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_rwn_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_data_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cfg_ready_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ch_cfg_valid_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ch_cfg_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ch_cfg_regaddr_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ch_cfg_data_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ch_cfg_ready_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_req_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_datasize_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_gnt_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_tx_valid_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_rx_datasize_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_rx_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_rx_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_rx_valid_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_data_rx_ready_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_req_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_datasize_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_gnt_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_data_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_valid_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_req_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_datasize_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_gnt_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_tx_valid_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_rx_datasize_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_rx_destination_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_rx_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_rx_valid_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_data_rx_ready_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/ext_events_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/main_leader_event_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/main_follower_event_o}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_period}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/period_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_clk_i}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_clk_sample}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/prescaler_reset_div10_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/prescaler_reset_div10_periph_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_last_reg}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_last_reg_next}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_last_reg_update}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_rose}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/command_period_valid_fell}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_fifo_clear_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_fifo_clear_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_fifo_lock_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_fifo_clear_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_fifo_lock_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_udma_tx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_udma_tx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_udma_tx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_tx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_tx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_tx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_io_tx_fifo_req}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_io_tx_fifo_gnt}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_rx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_rx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_rx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_fifo_clear_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_fifo_lock_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_fifo_clear_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_fifo_lock_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_fifo_clear_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_tx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_tx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_tx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_tx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_tx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_tx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/io_tx_fifo_req}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/io_tx_fifo_gnt}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_rx_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_rx_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_rx_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_command_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_command_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_command_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_cmd_req}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_cmd_gnt}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_cfg_tmp_regaddr_reg}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/udma_cfg_tmp_regaddr_reg_next}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_command_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_command_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_command_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/parser_state_reg}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/parser_state_reg_next}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_decode_group}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/cmd_decode_idx}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_clk_command_data}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_clk_command_ready}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_clk_command_valid}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/external_events_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_sof_receive_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_eof_receive_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_sof_send_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_eof_send_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_arbitration_lost_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_unexpected_framing_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_unlock_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_command_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unexpected_nack_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_arbitration_lost_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unexpected_framing_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unlock_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/soft_reset_event_i2c_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_sof_receive_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_eof_receive_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_sof_send_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_eof_send_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_arbitration_lost_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_unexpected_framing_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unexpected_nack_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_arbitration_lost_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unexpected_framing_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_command_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_to_sys_events_i2c}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/i2c_to_sys_events_sys}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/follower_unlock_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/leader_unlock_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/soft_reset_event_sys_clk}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sys_to_i2c_events_sys}
add wave -noupdate -group i2c0 {/tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_i2c_gen[0]/i_i2c/sys_to_i2c_events_i2c}
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/sys_clk_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/periph_clk_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/rstn_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dft_test_mode_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dft_cg_enable_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_en_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_en_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_rowlen_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_llx_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_lly_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_urx_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_rx_slice_ury_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/rstn_dcfifo_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_psel_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_penable_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_pwrite_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_pwdata_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_paddr_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_prdata_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/csi2_pready_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_psel_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_penable_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_pwrite_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_pwdata_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_paddr_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_prdata_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/dphy_pready_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_data_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_addr_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_valid_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_rwn_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_ready_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cfg_data_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_datasize_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_destination_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_data_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_valid_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_ready_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_datasize_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_destination_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_data_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_valid_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_ready_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_req_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_ack_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PADDR_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PWDATA_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PWRITE_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PSEL_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PRDATA_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_DPHY_PSLVERR_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_req_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_ack_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PADDR_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PWDATA_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PWRITE_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PSEL_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PRDATA_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/async_CSI2_PSLVERR_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/pixel_clk_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/apb_clk_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/cci_clk_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_write_token_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_read_pointer_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch0_data_asynch_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_write_token_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_read_pointer_o
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/data_rx_ch1_data_asynch_i
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_pixel_clk
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_cci_clk
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_apb_clk
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_pixel_update
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_pixel_data
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_pixel_ack
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_pixel_valid
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_cci_update
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_cci_data
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_cci_ack
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_cci_valid
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_apb_update
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_apb_data
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_apb_ack
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_clkdiv_apb_valid
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_rstn_dcfifo
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_rstn_dcfifo_sync
add wave -noupdate -group csi2 /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/ulpsoc_i/soc_peripherals_i/i_udma/i_csi2_if/s_rstn_sync_periph
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/pmu_csi2_isl_pd_ao_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/pmu_csi2_isl_ao_pd_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/pixel_clk_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/apb_clk_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/cci_clk_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rstn_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dft_test_mode_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dft_cg_enable_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_en_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_en_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_rowlen_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_llx_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_lly_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_urx_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rx_slice_ury_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/rstn_dcfifo_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_req_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_ack_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PADDR_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PWDATA_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PWRITE_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PSEL_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PRDATA_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_DPHY_PSLVERR_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_req_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_ack_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PADDR_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PWDATA_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PWRITE_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PSEL_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PRDATA_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/async_CSI2_PSLVERR_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch0_write_token_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch0_read_pointer_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch0_data_asynch_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch1_write_token_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch1_read_pointer_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/data_rx_ch1_data_asynch_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_clkp_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_clkn_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_datap0_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_datan0_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_datap1_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_datan1_io
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_vsync_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_hsync_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/RWM_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_scl_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_sda_i
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_sda_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_sda_oe_o
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch0_dc_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch0_dc_ready
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch0_dc
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch1_dc_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch1_dc_ready
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_data_rx_ch1_dc
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_id
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_type
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_vld_cnt
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_data
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_frame_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pixel_slice_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_valid_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_ready
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_data_full
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_id
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_type
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_valid
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_ready
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_data
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_csi2_pixel_fast_data_32b
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/r_get_msb
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pixel_clk_div2
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_psel_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_penable_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_pwrite_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_pwdata_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_paddr_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_prdata_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/dphy_pready_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_psel_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_penable_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_pwrite_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_pwdata_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_paddr_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_prdata_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/csi2_pready_int
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/r_vsync
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/r_enable
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_sof
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_vsync_out_vc0
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_hsync_out_vc0
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/r_rowcounter
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/r_colcounter
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pmu_csi2_isl_rst_ret_n
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pmu_csi2_isl_rst_ext_n
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pmu_csi2_isl_clkgt
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_rstn
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_pixel_clk
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_apb_clk
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_cci_clk
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_rstn_sync_pix
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_rstn_sync_apb
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_rstn_sync_cci
add wave -noupdate -group csi2_top /tb/pulp_chip_iface_wrap_i/i_dut/soc_domain_i/i_csi2_top_asynch/s_rstn_sync_pix2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 fs} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {22690 fs}
