# User Test
#------------------------------------

APP              = test
APP_SRCS        += deep_sleep.c
APP_INC	        +=
APP_CFLAGS      +=

# Output via UART
io=uart

PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
