# User Test
#------------------------------------

APP              = test
APP_SRCS        += helloworld.c
APP_INC	        +=
APP_CFLAGS      += #-DTRACE_PMU

# Output via UART
io=uart

PMSIS_OS=freertos

include $(RULES_DIR)/pmsis_rules.mk
